### ISSUE TITLE
Feature request: conceal whitespace below concealed characters

### ISSUE THREAD

**Issue by aarongable** [ehamberg/vim-cute-python#22]
Say I have the following code:

```
if some_bool and some_other_bool and foo(with, a, really
                                         long, argument, list):
```

When vim-cute-python kicks in, this gets converted to:

```
if some_bool ∧ some_other_bool ∧ foo(with, a, really
                                       long, argument, list):
```

And now my indentation of the continued arguments is off. It would be really cool if vim-cute-python could know how many characters are being concealed and conceal the same number of characters in each following line (as long as it's only concealing leading whitespace). So it would look like this:

```
if some_bool ∧ some_other_bool ∧ foo(with, a, really
                                     long, argument, list):
```

I realize that this is pretty far off the beaten path for `conceal`, but it would be a cool feature to investigate nonetheless.

**Comment by ehamberg** [comment]
Closing this issue since there hasn't been any activity in four years. Please reopen if anyone has any new information. :)
