### ISSUE TITLE
conflict with Plug 'vim-scripts/indentLine.vim'

### ISSUE THREAD

**Issue by vasyapupkin123456** [ehamberg/vim-cute-python#24]
hi Conceal       ctermfg=1  ctermbg=3

screenshot https://s10.postimg.org/b76l1a7cp/2016_08_11_230717_194643355.png

**Comment by vasyapupkin123456** [comment]
https://github.com/vim/vim/issues/1036

**Comment by ehamberg** [comment]
Not sure I understand this, but as far as I can see this can be solved by setting `g:indentLine_setConceal` for `indentLine`: <https://github.com/Yggdroot/indentLine/blob/master/README.md>.
