### ISSUE TITLE
No syntax highlighting on concealed chars

### ISSUE THREAD

**Issue by jdsutherland** [ehamberg/vim-cute-python#25]
I'm not getting syntax highlighting (colors) for concealed chars. However, if I `:source $MYVIMRC`, I do get syntax colors. Is this the intended behavior?

**Comment by ehamberg** [comment]
Nope. They should get syntax colouring. How did you install `vim-cute-python`?

**Comment by jdsutherland** [comment]
I installed via [vim-plug](https://github.com/junegunn/vim-plug). I'm using Neovim btw. I'm trying to think what else might be relevant.

**Comment by jdsutherland** [comment]
Removing `hi! link Conceal Operator` seems to everything work as expected.
