### ISSUE TITLE
len(S)   to    |S|

### ISSUE THREAD

**Issue by h-g-s** [ehamberg/vim-cute-python#26]
thanks for the amazing plugin. Would be possible to convert len(S)  into the mathematical notation |S|   (cardinality) ?

**Comment by ehamberg** [comment]
Unfortunately it's not possible to use `conceal` to surround something, as far as I know. (Or maybe it's possible by doing some tricks with `contained` in the syntax rules? Would love to know!)

In the `moresymbols` branch, `#` is used to signal length:
https://github.com/ehamberg/vim-cute-python/blob/ee3b23d6c89d31274078eb0cd289b291ebaca46a/after/syntax/python.vim#L43-L44
