### ISSUE TITLE
support for numpy

### ISSUE THREAD

**Issue by manu0600** [ehamberg/vim-cute-python#27]
Hi, I would suggest to add support to the numpy package by replacing those lines  :
`syntax match pyNiceOperator "\<\%(math\.\)\?sqrt\>" conceal cchar=√`
`syntax match pyNiceKeyword "\<\%(math\.\)\?pi\>" conceal cchar=π`
with the following :
`syntax match pyNiceOperator "\<\%(math\.\|np\.\)\?sqrt\>" conceal cchar=√`
`syntax match pyNiceKeyword "\<\%(math\.\|np\.\)\?pi\>" conceal cchar=π`
Thank you

**Comment by ehamberg** [comment]
Thanks for the suggestion! I think this makes sense. The downside is that people might no import numpy aliased to `np`, but if we match `numpy.sqrt` and `np.sqrt` (and the same for `pi`), that should cover most cases.
