### ISSUE TITLE
Relational Operators Doesn't  take effect

### ISSUE THREAD

**Issue by Mutska** [ehamberg/vim-cute-python#29]
**All works fine except these operators including "==".**
![test](https://user-images.githubusercontent.com/30533298/138628789-7884293a-6ec0-4f73-ad28-53b99ae8046a.PNG)
Am I missing something?

**Comment by ehamberg** [comment]
Don't think you're missing something. That should “just work”.

If you open vim with no file, insert “!=”, move the cursor to another line and then run the following commands, does that work?

```
:syntax match operator "!=" conceal cchar=≢
:setlocal conceallevel=1
```

**Comment by Mutska** [comment]
Yeah, that works, thanks. I put this in my init.vim 
![imagen](https://user-images.githubusercontent.com/30533298/138706586-a6bbc81b-b6e4-4a27-9c31-3b56079b91f0.png)
And voilà
![imagen](https://user-images.githubusercontent.com/30533298/138706709-4ae2039a-bf89-482d-aa3c-ab429550c64f.png)
Although I don't know why it doesn't work with the actual file only
